title: Learning to Generate 3D Shapes and Scenes
email: kai_wang@brown.edu
description: Website for the Workshop on Learning to Generate 3D Shapes and Scenes at ECCV 2022
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
