title: Panel Discussion : Intelligent Technologies and Systems for Palm Leaf Manuscript Understanding
email: ravi.kiran@iiit.ac.in
description: Website for the Panel Discussion: Intelligent Technologies and Systems for Palm Leaf Manuscript Understanding at ICFHR 2022
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
